addpath (userpath + "\swirl")
addpath (userpath + "\figures")

customColorOrder = [
    1   0   0;    % Red
    0   .8  0;    % Green
    0   0   1;    % Blue
    0   0   0;    % Black
    .8  .8  0;
    0   .8  .8;
    .8  0   .8];

set(groot, 'defaultFigureColor', [1 1 1], ...
           'defaultFigurePosition', [0 0 1000 1000]+100, ...
           'defaultFigureUnits','pixels' ,...
           'defaultFigureVisible', 'on', ... 
           'defaultFigurePaperPositionMode','auto', ...
           'defaultFigureColormap', bwrMap, ...
            ...
           'defaultTextInterpreter', 'latex', ...
           'defaultTextFontSize', 36 * 1.4, ...
           'defaultTextFontName', 'Times New Roman', ...
           'defaultTextUnits', 'normalized', ...
           ...
           'defaultAxesTickLabelInterpreter', 'latex', ...
           'defaultAxesFontName', 'Times New Roman', ...
           'defaultAxesFontSize', 36, ...
           'defaultAxesLineWidth', 1.5,...
           'defaultAxesBox', 'on', ...
           'defaultAxesBoxStyle', 'full', ... 
           'defaultAxesLabelFontSizeMultiplier', 1.4, ...
           'defaultAxesDataAspectRatio', [1 1 1], ...
           'defaultAxesPosition', [0.25 0.2 0.7 0.7], ...
           'defaultAxesNextPlot', 'add', ...
           'defaultAxesColorOrder', customColorOrder, ...
           ...
           'defaultLegendInterpreter', 'latex', ...
           'defaultLegendFontSize', 36, ...
           ...
           'defaultLineMarkerSize', 8, ...
           'defaultLineLineWidth', 3, ...
           ...
           'defaultSurfaceEdgeColor', 'interp', ...
           ...
           'defaultColorbarVisible', 'on');
clear
